config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'welcome/index'

  resources :charities

  resources :users

  root 'welcome#index'

  get 'about' => 'about#index'
  get 'contact' => 'contact#index'

end

app/models/charity.rb
class Charity < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
	 def index
    # @users = User.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charities_controller.rb
class CharitiesController < ApplicationController
  before_action :set_charity, only: [:show, :edit, :update, :destroy]

  # GET /charities
  # GET /charities.json
  def index
    @charities = Charity.all
  end

  # GET /charities/1
  # GET /charities/1.json
  def show
  end

  # GET /charities/new
  def new
    @charity = Charity.new
  end

  # GET /charities/1/edit
  def edit
  end

  # POST /charities
  # POST /charities.json
  def create
    @charity = Charity.new(charity_params)

    respond_to do |format|
      if @charity.save
        format.html { redirect_to @charity, notice: 'Charity was successfully created.' }
        format.json { render :show, status: :created, location: @charity }
      else
        format.html { render :new }
        format.json { render json: @charity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /charities/1
  # PATCH/PUT /charities/1.json
  def update
    respond_to do |format|
      if @charity.update(charity_params)
        format.html { redirect_to @charity, notice: 'Charity was successfully updated.' }
        format.json { render :show, status: :ok, location: @charity }
      else
        format.html { render :edit }
        format.json { render json: @charity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charities/1
  # DELETE /charities/1.json
  def destroy
    @charity.destroy
    respond_to do |format|
      format.html { redirect_to charities_url, notice: 'Charity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_charity
      @charity = Charity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def charity_params
      params.require(:charity).permit(:name, :url, :description, :vote)
    end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :social, :bio)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charities_helper.rb
module CharitiesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
<h1>About us</h1>

<p>Give Love Laugh enables small monthly donations from individuals to fund big causes for the public good.</p>

<h1>Team</h1>
<ul>
  <li>Conrad Steinbrueck: Product owner</li>
  <li>Exequiel Ramirez: Business development</li>
  <li>Stephen Doeve: Product designer</li>
  <li>Daniel Lu: Web developer</li>


</ul>

app/views/charities/_form.html.erb
<%= form_for(@charity) do |f| %>
  <% if @charity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@charity.errors.count, "error") %> prohibited this charity from being saved:</h2>

      <ul>
      <% @charity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :vote %><br>
    <%= f.number_field :vote %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/charities/edit.html.erb
<h1>Editing charity</h1>

<%= render 'form' %>

<%= link_to 'Show', @charity %> |
<%= link_to 'Back', charities_path %>

app/views/charities/index.html.erb
  <h1>Pick the causes you care about</h1>


  <h3>Clean Water</h3>

  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="range">
          <input type="range" name="range" min="1" max="100" value="50" onchange="range.value=value">
          <output id="range" class="pull-right">50</output>
        </div>
      </div>
    </div>
  </div>

  <br><br><br>


  <div class="charity-tile">
    <img src="../images/charity-water.png">
    <div class="charity-content">
      <h3 class="charity-name">Water for the People</h3>
      <p class="charity-description">we want all people to have safe, continuous water, and when they do, our job will be done. We want water for everyone, forever.</p>
      <p><a href="#">Website</a><p>
      <p>Donor statistics:</p>
      <div class="progress">
        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
          <span class="sr-only">40% Complete (success)</span>
        </div>
      </div>
    </div>
  </div><!-- end tile -->

  <div class="charity-tile">
    <img src="../images/charity-water2.png">
    <div class="charity-content">
      <h3 class="charity-name">Charity: Water</h3>
      <p class="charity-description">Our mission is to bring clean and safe drinking water to every person in the world.</p>
      <p><a href="#">Website</a><p>
      <p>Donor statistics:</p>
      <div class="progress">
        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
          <span class="sr-only">60% Complete (success)</span>
        </div>
      </div>
    </div>
  </div><!-- end tile -->


   <h3>Human Trafficking / Slavery</h3>

  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="range">
          <input type="range" name="range" min="1" max="100" value="50" onchange="range.value=value">
          <output id="range" class="pull-right">50</output>
        </div>
      </div>
    </div>
  </div>

  <br><br><br>


  <div class="charity-tile">
    <img src="../images/charity-human1.png">
    <div class="charity-content">
      <h3 class="charity-name">Free the Slaves</h3>
      <p class="charity-description">we want all people to have safe, continuous water, and when they do, our job will be done. We want water for everyone, forever.</p>
      <p><a href="#">Website</a><p>
      <p>Donor statistics:</p>
      <div class="progress">
        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
          <span class="sr-only">40% Complete (success)</span>
        </div>
      </div>
    </div>
  </div><!-- end tile -->

  <div class="charity-tile">
    <img src="../images/charity-human2.png">
    <div class="charity-content">
      <h3 class="charity-name">Not for Sale</h3>
      <p class="charity-description">Our mission is to bring clean and safe drinking water to every person in the world.</p>
      <p><a href="#">Website</a><p>
      <p>Donor statistics:</p>
      <div class="progress">
        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
          <span class="sr-only">60% Complete (success)</span>
        </div>
      </div>
    </div>
  </div><!-- end tile -->

  <div class="charity-tile">
    <img src="../images/charity-human3.png">
    <div class="charity-content">
      <h3 class="charity-name">End It Movement</h3>
      <p class="charity-description">Our mission is to bring clean and safe drinking water to every person in the world.</p>
      <p><a href="#">Website</a><p>
      <p>Donor statistics:</p>
      <div class="progress">
        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
          <span class="sr-only">60% Complete (success)</span>
        </div>
      </div>
    </div>
  </div><!-- end tile -->

   <h3>Animal Rescue</h3>

  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="range">
          <input type="range" name="range" min="1" max="100" value="50" onchange="range.value=value">
          <output id="range" class="pull-right">50</output>
        </div>
      </div>
    </div>
  </div>

  <br><br><br>


  <div class="charity-tile">
    <img src="../images/charity-animal1.png">
    <div class="charity-content">
      <h3 class="charity-name">ASPCA</h3>
      <p class="charity-description">we want all people to have safe, continuous water, and when they do, our job will be done. We want water for everyone, forever.</p>
      <p><a href="#">Website</a><p>
      <p>Donor statistics:</p>
      <div class="progress">
        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
          <span class="sr-only">40% Complete (success)</span>
        </div>
      </div>
    </div>
  </div><!-- end tile -->

  <div class="charity-tile">
    <img src="../images/charity-animal2.png">
    <div class="charity-content">
      <h3 class="charity-name">IAPF</h3>
      <p class="charity-description">Our mission is to bring clean and safe drinking water to every person in the world.</p>
      <p><a href="#">Website</a><p>
      <p>Donor statistics:</p>
      <div class="progress">
        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
          <span class="sr-only">60% Complete (success)</span>
        </div>
      </div>
    </div>
  </div><!-- end tile -->

    <div class="charity-tile">
    <img src="../images/charity-animal3.png">
    <div class="charity-content">
      <h3 class="charity-name">Best Friends Society</h3>
      <p class="charity-description">Our mission is to bring clean and safe drinking water to every person in the world.</p>
      <p><a href="#">Website</a><p>
      <p>Donor statistics:</p>
      <div class="progress">
        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
          <span class="sr-only">60% Complete (success)</span>
        </div>
      </div>
    </div>
  </div><!-- end tile -->

   <h3>Emergency Relief</h3>

  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="range">
          <input type="range" name="range" min="1" max="100" value="50" onchange="range.value=value">
          <output id="range" class="pull-right">50</output>
        </div>
      </div>
    </div>
  </div>

  <br><br><br>


  <div class="charity-tile">
    <img src="../images/charity-relief1.png">
    <div class="charity-content">
      <h3 class="charity-name">Redeeming Soles</h3>
      <p class="charity-description">we want all people to have safe, continuous water, and when they do, our job will be done. We want water for everyone, forever.</p>
      <p><a href="#">Website</a><p>
      <p>Donor statistics:</p>
      <div class="progress">
        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
          <span class="sr-only">40% Complete (success)</span>
        </div>
      </div>
    </div>
  </div><!-- end tile -->

  <div class="charity-tile">
    <img src="../images/charity-relief2.png">
    <div class="charity-content">
      <h3 class="charity-name">DisasterOne</h3>
      <p class="charity-description">Our mission is to bring clean and safe drinking water to every person in the world.</p>
      <p><a href="#">Website</a><p>
      <p>Donor statistics:</p>
      <div class="progress">
        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
          <span class="sr-only">60% Complete (success)</span>
        </div>
      </div>
    </div>
  </div><!-- end tile -->

  <br>
  <br>
  <br>

  <a href="#card" class="btn btn-primary btn-lg reveal-block" role="button"><i class="fa fa-arrow-right fa-in-button"></i> Payment Options</a>
  

<br><br><br><br><br>



    

<a name="card"></a>
<br><br><br><br><br><br><br><br><br><br><br><br>

<div class="container">
  <form class="form-horizontal" role="form">
    <fieldset>
      <div class="form-group">
        <label class="col-sm-3 control-label" for="card-holder-name">Name on Card</label>
        <div class="col-sm-9">
          <input type="text" class="form-control" name="card-holder-name" id="card-holder-name" placeholder="Card Holder's Name">
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-3 control-label" for="card-number">Card Number</label>
        <div class="col-sm-9">
          <input type="text" class="form-control" name="card-number" id="card-number" placeholder="Debit/Credit Card Number">
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-3 control-label" for="expiry-month">Expiration Date</label>
        <div class="col-sm-9">
          <div class="row">
            <div class="col-xs-3">
              <select class="form-control col-sm-2" name="expiry-month" id="expiry-month">
                <option>Month</option>
                <option value="01">Jan (01)</option>
                <option value="02">Feb (02)</option>
                <option value="03">Mar (03)</option>
                <option value="04">Apr (04)</option>
                <option value="05">May (05)</option>
                <option value="06">June (06)</option>
                <option value="07">July (07)</option>
                <option value="08">Aug (08)</option>
                <option value="09">Sep (09)</option>
                <option value="10">Oct (10)</option>
                <option value="11">Nov (11)</option>
                <option value="12">Dec (12)</option>
              </select>
            </div>
            <div class="col-xs-3">
              <select class="form-control" name="expiry-year">
                <option value="13">2013</option>
                <option value="14">2014</option>
                <option value="15">2015</option>
                <option value="16">2016</option>
                <option value="17">2017</option>
                <option value="18">2018</option>
                <option value="19">2019</option>
                <option value="20">2020</option>
                <option value="21">2021</option>
                <option value="22">2022</option>
                <option value="23">2023</option>
              </select>
            </div>
          </div>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-3 control-label" for="cvv">Card CVV</label>
        <div class="col-sm-3">
          <input type="text" class="form-control" name="cvv" id="cvv" placeholder="Security Code">
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-3 col-sm-9">
          <a href="#thankyou" class="btn btn-primary btn-lg reveal-block" role="button"><i class="fa fa-arrow-right fa-in-button"></i> Pay now</a>
        </div>
      </div>
    </fieldset>
  </form>
</div>



<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

<a name="thankyou"></a>
<br><br><br><br><br><br><br><br><br><br><br><br>
<h1 class="text-center"><i class="fa fa-star fa-spin"></i></h1>
<h1 class="text-center">Thank You!</h1>
<h3 class="text-center">With your help, this world will be a better place.</h3>
<p class="text-center">We will send you an email of the transaction summary. <br>You may check back at any time to see your past charitable contributions.</p>

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

app/views/charities/new.html.erb
<h1>New charity</h1>

<%= render 'form' %>

<%= link_to 'Back', charities_path %>

app/views/charities/show.html.erb
<div class="container">
  <h3>Pick the causes you care about</h3>
  
</div>

app/views/contact/index.html.erb
<div class="page-header">
  <h1>Contact</h1>
</div>

<div class="row">
  <div class="col-md-8">
  	<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6610.199584839492!2d-118.16933724770915!3d34.066956027470596!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80c2c5a285c456e3%3A0x2afcd137f76a39d6!2sCalifornia+State+University+Los+Angeles!5e0!3m2!1sen!2sus!4v1403996684155" width="500" height="500" frameborder="0" style="border:0"></iframe>
  </div>
  <div class="col-md-4">
  	<p>We want to hear from caring people like you.</p>
  	<p><strong>Give Love Laugh</strong><br>
  		5151 State University Dr,<br>
  		Los Angeles, CA 90032
  	</p>
  	<p>Phone: (323) 555-1212</p>
  	<p>Email: <a href="info@givelovelaugh.org">info@givelovelaugh.org</a></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Give Love Laugh</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="shortcut icon" href="../images/favicon.png" type="image/x-icon" />
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "/" do %>
        <img src="../images/givelovelaugh_logo.png">
        <% end %>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><a href="#">How This Works</a></li>
          <li><a href="contact">Contact</a></li>

          <% if user_signed_in? %>
<!--           <li><a href=""><strong><%= current_user.email %></a></strong>. -->
          <li><%= link_to edit_user_registration_path do %>
            <%= current_user.email %>
            <% end %>
          </li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete  %></li>
          
          <% else %>

          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
          <% end %>

        </ul>
      </div>
    </div>
  </div>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable" do %>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= msg %>
      <% end %>
    <% end %>
    <!-- Devise goodies -->
<!--     <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %> -->
    <!-- End Devise goodies -->
    <%= yield %>
  </div>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :social %><br>
    <%= f.text_field :social %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Social</th>
      <th>Bio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><a href="https://twitter.com/<%= user.social %>"><%= user.social %></a></td>
        <td><%= user.bio %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Social:</strong>
  <a href="https://twitter.com/<%= @user.social %>"><%= @user.social %></a>
</p>

<p>
  <strong>Bio:</strong>
  <%= @user.bio %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<div class="jumbotron text-center">
	<h1>Doing more, together</h1>
	<p><a class="btn btn-primary btn-lg" role="button" href="/charities">
	         Start Giving Today</a></p>
</div>

 <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h1 class="text-center landing-icon"><i class="glyphicon glyphicon-heart"></i></h1>
          <h2>Causes You Care About</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">See Charities &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h1 class="text-center landing-icon"><i class="glyphicon glyphicon-ok"></i></h1>
          <h2>No Amount is Too Small</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h1 class="text-center landing-icon"><i class="glyphicon glyphicon-upload"></i></h1>
          <h2>$1,000,000 and Counting</h2>
          <p>Give Love Laught has collected more than $1,000,000 for great causes and local charities. Contribute today and make our world a better place.</p>
          <p><a class="btn btn-default" href="#" role="button">Get Started &raquo;</a></p>
        </div>
      </div>

      <hr>

      <footer>
        <p>&copy; Give Love Laugh Foundation. Produced during Startup Weekend 2014 at CSULA, powered by Google for Entrepreneurs.</p>
      </footer>
    </div> <!-- /container -->